# Generated by Django 5.2.8 on 2025-12-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publicado',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fecha',
            new_name='updated_at',
        ),
    ]
