# Generated by Django 5.2.8 on 2025-12-04 19:37

import apps.blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='posts/default/post-default.jpg', upload_to=apps.blog.models.get_image_filename),
        ),
    ]
