# Generated by Django 5.2.8 on 2025-12-05 04:07

import apps.blog.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_allow_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='post/default/post-default.png', upload_to=apps.blog.models.get_image_filename),
        ),
    ]
