# Generated by Django 5.2.8 on 2025-12-08 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_category_alter_postimage_image'),
        ('school', '0013_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
