# Generated by Django 5.2.8 on 2025-12-05 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postimage_active_postimage_created_at_and_more'),
        ('school', '0009_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
