# Generated by Django 5.2.8 on 2025-12-05 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_school'),
        ('school', '0009_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
