# Generated by Django 5.2.8 on 2025-12-13 17:04

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='posts/default/post-default.jpg', upload_to=apps.blog.models.get_image_filename),
        ),
    ]
