# Generated by Django 5.2.8 on 2025-12-02 04:22

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/default/avatar-default.png', upload_to=apps.user.models.get_avatar_filename),
        ),
        migrations.AddField(
            model_name='user',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='relacion_escuela',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
