# Generated by Django 5.2.8 on 2025-12-02 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_school_id'),
        ('user', '0002_user_avatar_user_ciudad_user_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.school'),
        ),
    ]
