# Generated by Django 5.2.8 on 2025-12-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_escuela'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fecha_nacimiento',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ciudad',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='relacion_escuela',
            new_name='related_school',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='escuela',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tipo',
            new_name='type',
        ),
    ]
