# Generated by Django 5.2.8 on 2025-12-04 16:54

import apps.user.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_fecha_nacimiento_user_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='img/default-user.png', upload_to=apps.user.models.get_avatar_filename),
        ),
    ]
