# Generated by Django 5.2.8 on 2025-12-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_fecha_nacimiento_user_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='related_school',
            field=models.CharField(blank=True, choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('directivo', 'Directivo'), ('padre', 'Padre / Madre'), ('otro', 'Otro')], max_length=100),
        ),
    ]
