# Generated by Django 5.2.8 on 2025-11-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
