# Generated by Django 5.2.8 on 2025-12-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_rating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='school',
            name='rating_count',
        ),
    ]
