# Generated by Django 5.2.8 on 2025-12-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='reviews',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_level',
            field=models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=20, null=True),
        ),
    ]
