# Generated by Django 5.2.8 on 2025-12-04 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_school_address_school_reviews_school_school_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(default='Falsa 123', max_length=120),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_level',
            field=models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='school.school')),
            ],
        ),
    ]
