# Generated by Django 5.2.8 on 2025-12-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_school_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default='comentario', max_length=500),
            preserve_default=False,
        ),
    ]
