# Generated by Django 5.2.8 on 2025-12-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='management_type',
            field=models.CharField(blank=True, choices=[('publica', 'Pública'), ('privada', 'Privada')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
