# Generated by Django 5.2.8 on 2025-12-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
