# Generated by Django 5.2.8 on 2025-12-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_school_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
