# Generated by Django 5.2.8 on 2025-12-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_school_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
