# Generated by Django 5.2.8 on 2025-12-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, default='schools/default/school-default.png', upload_to='schools/'),
        ),
    ]
