# Generated by Django 5.2.8 on 2025-12-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
