# Generated by Django 5.2.8 on 2025-12-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_schoolratingareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='school',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
