# Generated by Django 5.2.8 on 2025-12-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_school_rating_school_rating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolrating',
            name='value',
        ),
        migrations.AddField(
            model_name='schoolrating',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolrating',
            name='bienestar',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolrating',
            name='cultura',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolrating',
            name='pedagogica',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolrating',
            name='recursos',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schoolrating',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_areas', to='school.school'),
        ),
        migrations.DeleteModel(
            name='SchoolRatingAreas',
        ),
    ]
